### ISSUE TITLE
gittle.rm not working

### ISSUE THREAD

**Issue by magic890** [scragg0x/realms-wiki#61] opened 2015-07-13 12:23 UTC
It seems that `gittle.rm()` is not working. See this lines:

* https://github.com/scragg0x/realms-wiki/blob/master/realms/modules/wiki/models.py#L133
* https://github.com/scragg0x/realms-wiki/blob/master/realms/modules/wiki/models.py#L159

After that command, in the commit there isn't the removed file and the file persist on file system.

Do you know why this is not working and how to solve this issue?

**Comment by scragg0x** [comment] 2015-07-13 13:22
Can you confirm that the web app has permission to remove the file?  It's possible it only has permissions to the .git dir.

**Comment by magic890** [comment] 2015-07-13 15:08
The `wiki` and `wiki/.git` directories have `755`.
The files have `644`.

I tried also to change files permission to `777`, without success.

**Comment by scragg0x** [comment] 2015-07-15 14:15
@magic890 

It's possible I have never tried to delete a page via gittle.  Did you manage to get it working?

**Comment by magic890** [comment] 2015-07-16 10:30
I'm working on it, using this [repo](https://github.com/goodotcom/realms-wiki).
When it'll work I'll suggest a PR.

**Comment by alvinchow86** [comment] 2015-09-27 22:06
I noticed this problem as well. I think the problem is that at https://github.com/scragg0x/realms-wiki/blob/master/realms/modules/wiki/models.py#L106;  I added some debug statements and noticed that `old_name` and `new_name` are the same . This is called from https://github.com/scragg0x/realms-wiki/blob/master/realms/modules/wiki/models.py#L106

**Comment by alvinchow86** [comment] 2015-09-28 07:01
FYI https://github.com/scragg0x/realms-wiki/pull/83

**Comment by gazpachoking** [comment] 2016-07-26 00:38
Believe this is fixed now.

**Closed by gazpachoking** 2016-07-26 00:38 UTC
